version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: archdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
      - redis
    command: >
      sh -c "sleep 10 && python init_db/init_db_mongo.py && python init_db/init_test_db.py && uvicorn jwt:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
  mongo_data:
  redisdata: